### ISSUE TITLE
bower registration?

### ISSUE THREAD

**Issue by nschloe** [GitbookIO/kramed#26]
When including kramed into my `bower.json`,
```
"dependencies": {
  "kramed": "0.4.6"
}
```
I'm getting
```
bower kramed#0.4.6                           ENOTFOUND Package kramed not found
```
Has it been [registered](http://bower.io/docs/creating-packages/#register) yet?

Also, it appears that the version in kramed's `bower.json` is somewhat outdated (0.4.6 vs. 0.5.1 in `package.json`).

**Comment by andrenarchy** [comment]
What's the status here?

**Comment by mdayaram** [comment]
Also interested in this.  Is there an ETA to get `kramed` registered to bower?

**Comment by AaronO** [comment]
@mdayaram @andrenarchy @nschloe Done, it should now be registered !

That said, I would recommend using `browserify` instead of `bower`, `browserify` is much cleaner and ultimately what all the JS community is switching too.

**Comment by nschloe** [comment]
Thanks! [The latest release](https://github.com/GitbookIO/kramed/tree/66f4dec4e5f7a66e0e23e2cfcbb1f8ea5ce66127) still lists
```
  "version": "0.4.6",
```
in its `bower.json` which is somewhat awkward, but other than that it seems fine.
