### ISSUE TITLE
Mathematics - display should be allowed within paragraphs

### ISSUE THREAD

**Issue by ErnWong** [GitbookIO/kramed#3]
Yup. That sounds contradictory, but due to the fact that it is accepted to treat mathematics as part of sentences, it totally makes sense for mathematical equations, even display/block mathematics, to be inside a paragraph.

Have a look at the image in this page to get the idea:
http://superuser.com/questions/601042/how-to-insert-display-equations-in-a-word-document-without-breaking-a-paragraph

Here's a small discussion about it in MathJax google groups:
https://groups.google.com/forum/#!topic/mathjax-users/hnNmdpAm_4Q

From what I saw in kramed.js, it looks like you can only use double dollar signs `$$` for maths delimiters: both display and inline, determined by whether it is separated from the paragraph or not. This could possibly be solved with/along with GitbookIO/plugin-mathjax#5.

Thanks!

**Comment by AaronO** [comment]
@ErnWong `kramed` already accepts both inline and block math. I'm not sure what exactly isn't working as expected for you. Could you elaborate ?

**Comment by AaronO** [comment]
@ErnWong Closing this, to keep things clean. We switched to `$$` to disambiguate with single dollar signs `$`, so inline math should work with `$$`.

Let me know if this is not the case.
