### ISSUE TITLE
TypeError - Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by pun-isher** [GitbookIO/kramed#30]
I have been primarily using the web editor, so I am not sure what would cause this particular error. The first chapter of my book failed to build. 

--Output dump--

Downloading source
Extracting source
GitBook version is 2.6.3 
Tweaking book.json
Installing plugins
info: 2 plugins to install 
info: No version specified, resolve plugin comment 
info: install plugin comment from npm (gitbook-plugin-comment) with version 0.2.0 
gitbook-plugin-comment@0.2.0 node_modules/gitbook-plugin-comment
info: >> plugin comment installed with success 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Building Site, will upload
info: loading book configuration....OK 
info: load plugin gitbook-plugin-comment ....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: >> 6 plugins loaded 
info: start generation with website generator 
info: clean website generatorOK 

TypeError: Cannot call method 'toLowerCase' of undefined
Please report this to https://github.com/GitbookIO/kramed. (In file 'README.md')

**Comment by pun-isher** [comment]
Welp. I reran the building process and there were no further errors. This issue can be closed.

**Comment by AaronO** [comment]
@pun-isher Yep, I accidentally introduced that regression in `kramed`'s `0.5.4` release last night and fixed it early this morning in the `0.5.5` release: https://github.com/GitbookIO/kramed/commits/master

Sorry for the inconvenience, but it should all be good now :)
