### ISSUE TITLE
Bulleted List and Numbered List merged

### ISSUE THREAD

**Issue by kanekotic** [GitbookIO/kramed#34]
While writing using GitBook I wanted to have a numbered list and in one of the items have a list of bullet points. If they are writen at the same level numbered and bulleted get merged into a unique numbered list. As you can see in the next screenshot:

![capture](https://cloud.githubusercontent.com/assets/3071208/12579719/58ea4bc8-c42a-11e5-954a-13fc2e1741aa.PNG)

A workaround for now is  tab the bulleted list it will work correctly (just the style of the bullets is not the level 1 type).

**Comment by alvarolorentedev** [comment]
Staled
