### ISSUE TITLE
convert links to footnotes

### ISSUE THREAD

**Issue by piranna** [GitbookIO/kramed#7]
Add option so inline links are converted and rendered as footnotes. This would allow to show them when printing. Also, instead of just convert them as footnotes, they could be arranged in a structure and collected with other ones so GitBook could use it to create a bibliography appendix.

**Comment by AaronO** [comment]
@piranna I think this should be handled as part of `gitbook`, since it's it more `gitbook` specific rather than related to a markdown parser/renderer.

Feel free to open up an issue on `gitbook` as soon as the `2.0.0` is out :)

**Comment by piranna** [comment]
I though it would make sense here since kramed has already support for footnotes, but from a parser-output scheme, it's obviously a output (GitBook) issue :-) I'll open it now.
